version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
shallow_clone: true
build_script:
- ps: choco pack
artifacts:
- path: '**\*.nupkg'
  name: ChocoPackage
deploy:
- provider: NuGet
  server: https://push.chocolatey.org/
  api_key:
    secure: NwN4m3lQg5sfkTG4qKDwSSC+jR3bKLkW6ofeGTPZ4k8MtusQSSG5rTpKObwzw2Po
  skip_symbols: true
  artifact: '**\*.nupkg'