version: '{build}'
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
build_script:
- ps: choco pack
artifacts:
- path: '**\*.nupkg'
  name: ChocoPackage
deploy:
- provider: NuGet
  server: https://push.chocolatey.org/
  api_key:
    secure: %key%
  skip_symbols: true
  artifact: ChocoPackage
